docs(community): adds governance pages
spinnaker/spinnaker.github.io pull request #1034
Opened 2018-10-03 20:15 UTC by skim1420

2018-10-03 20:39 UTC, dorbin requested changes
The editorial stuff is all optional, @skim1420 , but I *am* confused by that first paragraph.

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +The Spinnaker OSS project is run by a group of appointed members who hold specific roles, managed by the technical oversight committee. The steering committee manages the governance structure of the
"is run by a group of appointed members"
Is this the steering committee? The way this first sentence sounds, the (steering committee?) is managed by the technical oversight committee.

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +The broader community is organized around a set of special interest groups (SIGs) focused on particular areas of interest.
"...is organized *into* a set of" sigs?

Link from "special interest groups (SIGs)" to the SIGs section below?

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +The steering committee’s responsibility and function lies in the continual shaping of the governance structure to serve the project’s needs best.
"The steering committee is responsible for shaping governance to best serve the project's needs."

(This is the clearer, less wordy, less redundant way to say the same thing, but your way sounds more idiomatic of these sorts of things, so if you'd like the keep the language as is, feel free, except still move "best" to before "serve.")

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +* Ratify new SIGs
Periods after all or after none.

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +Current SC members:
You've got a colon after this one, but not after any of the others on this page. What about using heading-level 4 for all.

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +The steering committee is initially seeded by Netflix and Google as the project matures and its structure stabilizes. We will leave further details such as number of seats, qualifications, tenure, ap
s/as/while/

2018-10-03 20:39 UTC, dorbin commented on community/governance/index.md
> +SIGs (special interest groups) are created as community interest and demand around particular topics become self evident, and continue on as their relevance and needs do. SIGs and their leads are rat
s/self evident/evident/

s/as their relevance and needs do/as needed/

2018-10-04 16:59 UTC, merged

2018-10-05 03:49 UTC, skim1420 commented on community/governance/index.md
> +The Spinnaker OSS project is run by a group of appointed members who hold specific roles, managed by the technical oversight committee. The steering committee manages the governance structure of the
This refers to reviewers and approvers.