docs(provider/oracle): document Oracle Clould Object Storage
spinnaker/spinnaker.github.io pull request #1044
Opened 2018-10-09 17:49 UTC by shihchang

document Oracle Clould Object Storage config

2018-10-09 18:11 UTC, shihchang commented
@markxnelson

2018-10-09 18:25 UTC, dorbin requested changes
Hi, @shihchang 
Thanks for the doc! I've added some suggestions.

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +redirect_from: /setup/storage/oracle/
I don't think this redirect is needed, because we didn't have an Oracle page previously. It's a copy-and-paste, right? The other ones have the redirect because I reorganized the structure.

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +- A user in IAM for the person or system who will be using the Spinnaker, and the user must be granted the access to Object Storage or in one IAM group with permissions of Object Storage.
s/using the Spinnaker, and the user/using Spinnaker. That user/

Also, remove "the" before "access"

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +See [Managing Regions](https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingregions.htm){:target="\_blank"}.
I can't preview how this is going to format in the generated html, but I suspect it's not going to look quite right. 

Could you change the "-" to "*", add a blank line between the list item and the paragraph under it (the one that starts with "See [link]"), and indent that same paragraph three spaces? That should format it correctly.

This suggestion is for all of these list items.

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +- A bucket to store persistent data within the Object Storage namespace. If you do not already have a bucket that you want to use, Halyard will create one for you (either with the `--bucket` name pro
Do you also want to link to the Halyard command reference for this?

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +See [Managing Regions](https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingregions.htm){:target="\_blank"}.
Also, you'll need a blank line between that paragraph and the next list item.

2018-10-09 18:25 UTC, dorbin commented on setup/install/storage/oracle.md
> +- A bucket to store persistent data within the Object Storage namespace. If you do not already have a bucket that you want to use, Halyard will create one for you (either with the `--bucket` name pro
Also, should be `--bucket-name` not `--bucket`, right?

2018-10-09 19:50 UTC, shihchang commented on setup/install/storage/oracle.md
> +redirect_from: /setup/storage/oracle/
removed redirect_from. I noticed an issue when I ran docker to see how it looks like-  when I first time click on the "4. Choose a Storage Service" on the left side navigation list, it expands the list of "Overview, Azure Storage, ..." but there is no Oracle Object Storage (the new one I just added). But when I click on the "Overview", then the "Oracle Object Storage" does show up in the list. Then I try to look at how I did differently from others.

2018-10-09 19:51 UTC, shihchang commented on setup/install/storage/oracle.md
> +- A user in IAM for the person or system who will be using the Spinnaker, and the user must be granted the access to Object Storage or in one IAM group with permissions of Object Storage.
Fixed. Also fixed a similar sentence in my previous commit of Oracle Provider"

2018-10-09 19:56 UTC, shihchang commented on setup/install/storage/oracle.md
> +See [Managing Regions](https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingregions.htm){:target="\_blank"}.
Reformatted as you suggested.

I did run docker locally to see how the real format look like, and the "-" list does look fine as https://www.spinnaker.io/setup/install/providers/oracle/
I will also reformat this Oracle Provider one to the way you suggested

2018-10-09 19:57 UTC, shihchang commented on setup/install/storage/oracle.md
> +- A bucket to store persistent data within the Object Storage namespace. If you do not already have a bucket that you want to use, Halyard will create one for you (either with the `--bucket` name pro
Fixed to --bucket-name.
I add the link of command reference to the hal command section.

2018-10-09 20:18 UTC, dorbin commented on setup/install/storage/oracle.md
> +See [Managing Regions](https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingregions.htm){:target="\_blank"}.
Yeah, I didn't check other articles' source to see how that looked. So yeah, looking at the one you linked, that's acceptable. You can change it or not--your option.

2018-10-09 20:19 UTC, dorbin commented on setup/install/storage/oracle.md
> +- A bucket to store persistent data within the Object Storage namespace. If you do not already have a bucket that you want to use, Halyard will create one for you (either with the `--bucket` name pro
👍

2018-10-09 20:20 UTC, dorbin approved these changes

2018-10-11 17:18 UTC, ezimanyi approved these changes
Looks good!  I had one small comment, but don't think it should block merging.

2018-10-11 17:18 UTC, ezimanyi commented on setup/install/storage/oracle.md
> +If you have enabled [Oracle Cloud provider](/setup/install/providers/oracle/) in Spinnaker, you may use the same region, Tenancy’s OCID, user’s OCID, Compartment's OCID, private key file, and fingerp
For consistency, suggest using ASCII apostrophe (') for all apostrophes and letting the front-end make it a curly apostrophe.

2018-10-11 17:18 UTC, merged