Add codelab for pub/sub to CF
spinnaker/spinnaker.github.io pull request #1132
Opened 2018-12-04 17:38 UTC by fifthposition

@dorbin @lwander Last PR for a while (I think). Apologies for constant pinging. :)

2018-12-05 17:33 UTC, fifthposition commented
Ping :D

2018-12-05 18:05 UTC, dorbin commented
@okundzich
Another one for you to take a look at?

2018-12-05 19:22 UTC, okundzich commented
Looks good. @dorbin.

2018-12-05 21:27 UTC, dorbin requested changes
@fifthposition 
I like how you number the headings, a good idea when the whole article is an overarching procedures, but it's not short.

Inisde each numbered-heading section, you might number the (sub-)procedure. I think if you start them all with `a` they'll auto number a., b., c. But preview it to be sure, if you're set up  to do so.

2018-12-05 21:27 UTC, dorbin commented on guides/tutorials/codelabs/pubsub-to-cf/index.md
> +Following the GCP documentation on Creating and Managing Service Accounts, create a new service account, giving it the Storage Admin (`roles/storage.admin`) and Pub/Sub Subscriber (`roles/pubsub.subs
@fifthposition can you link to that doc from here?

2018-12-05 21:44 UTC, fifthposition commented on guides/tutorials/codelabs/pubsub-to-cf/index.md
> +Following the GCP documentation on Creating and Managing Service Accounts, create a new service account, giving it the Storage Admin (`roles/storage.admin`) and Pub/Sub Subscriber (`roles/pubsub.subs
Ooh. Good catch. Thanks!

2018-12-05 21:45 UTC, fifthposition commented
Thanks for review @dorbin. Made changes!

2018-12-06 17:19 UTC, fifthposition commented
@dorbin LMK how it looks now. I can't have it auto-number subsections but I tried doing it by hand.

2018-12-06 18:47 UTC, dorbin approved these changes
👍 
Thanks, @fifthposition

2018-12-07 21:08 UTC, merged