Draft proposal option 3 and Halyard step structure
spinnaker/spinnaker.github.io pull request #1665
Opened 2020-01-14 04:50 UTC by aleon1220

1-A proposal to have a section option 3 that describes the steps to be taken in AWS console manually. I am happy to add the screenshots that match the generic names 

2-A new Halyard section with description of the general steps that should be taken inside halyard

2020-01-14 19:33 UTC, 317brian requested changes

2020-01-14 19:33 UTC, brian-armory commented on setup/install/providers/aws/aws-ec2.md
> +After the AWS IAM user, roles, policies and trust relationship has been set up, the next step is to add the AWS configurations to spinnaker via Halyard CLI.
capital 'S' for Spinnaker

2020-01-14 19:33 UTC, brian-armory commented on setup/install/providers/aws/aws-ec2.md
> +* Access the Halyard Pod
These steps should be an ordered list. Also, can we be explicit about each step, e.g. 

```
Apply the configurations to spinnaker
```

should become

```
4. Apply the configurations to Spinnaker: `hal deploy apply`. 
```

Period at the end of each list item too.

2020-01-15 02:08 UTC, aleon1220 reviewed
thank you. I agree with the changes

2020-01-21 00:20 UTC, aleon1220 reviewed
It looks good to me.

2020-01-21 00:30 UTC, brian-armory commented
Hi @aleon1220, there isn't a commit with my suggested updates.

2020-01-24 18:21 UTC, 317brian approved these changes

2020-01-24 18:38 UTC, merged