Clarify artifact format usage with spin CLI
spinnaker/spinnaker.github.io pull request #1706
Opened 2020-02-11 23:01 UTC by ejsuncy

Because it took me far too long to discover how to use this option correctly.

2020-02-12 21:09 UTC, dorbin reviewed
Thanks, @ejsuncy. A few editorial comments.

@louisjimenez , fyi and ptal

2020-02-12 21:09 UTC, dorbin commented on reference/artifacts/index.md
> +### Example for Providing Artifacts with `spin` CLI
```suggestion
### Example for providing artifacts with `spin` CLI
```

2020-02-12 21:09 UTC, dorbin commented on reference/artifacts/index.md
> +When executing pipelines with the `spin` CLI, the `-t, --artifacts-file` option expects a valid json file containing artifact definitions. For example, you can call `spin pipeline execute --applicati
```suggestion
When you execute pipelines with the [`spin` CLI](/guides/spin/), the `-t, --artifacts-file` option expects a valid JSON file containing artifact definitions. For example, you can call...

```
`spin pipeline execute --application ${APPLICATION} --name ${PIPELINE} --parameter-file ${PARAMETER_FILE_PATH} --artifacts-file ${ARTIFACTS_FILE_PATH}`
```

...with the contents of the file at `${ARTIFACTS_FILE_PATH}` as follows:
```

2020-02-12 22:19 UTC, louisjimenez requested changes
Example looks good. Were the editorial changes proposed by @dorbin accidentally overwritten?

2020-02-12 22:27 UTC, ejsuncy commented
oh Github...*sigh*. I'll try again

2020-02-12 22:38 UTC, ejsuncy commented
OK, that looks better.

2020-02-12 22:49 UTC, louisjimenez approved these changes

2020-02-13 15:06 UTC, dorbin approved these changes

2020-02-13 15:06 UTC, merged