Expanded description on the aws iam concepts
spinnaker/spinnaker.github.io pull request #1804
Opened 2020-04-17 01:01 UTC by aleon1220

- Describes how Halyard interacts with AWS IAM
- Explains the 2 aws accounts for aws provider
- Reminds user that AWS IAM structure must be set prior to deploy spinnaker
- Adds reference to AWS IAM doc

2020-04-27 16:45 UTC, 317brian requested changes

2020-04-27 16:45 UTC, 317brian commented on setup/install/providers/aws/index.md
> +There are two types of Accounts in the Spinnaker AWS provider: __AWS Managing__ account and __AWS Managed__ account(s)
Missing period at the end

2020-04-27 16:45 UTC, brian-armory commented on setup/install/providers/aws/index.md
> +1. __AWS Managing__ account. There is always exactly one managing account, this
Some minor things in this:

- period after `managing account` instead of comma
- replace `assumes roles` with `uses to assume roles`

2020-04-28 00:32 UTC, aleon1220 reviewed
thanks

2020-04-28 00:33 UTC, aleon1220 commented
@brian-armory i am not sure if i accepted your changes or not since i am using github UI to facilitate.
Thanks for reviewing my PR

2020-04-28 17:41 UTC, brian-armory commented
Oh, I didn't use the suggestion feature in GitHub cause the source repo was deleted. Wasn't sure how that would work/not work. You have to manually make the changes.

2020-04-28 23:55 UTC, aleon1220 reviewed
thank you. I cannot really Approve.

2020-04-29 18:16 UTC, brian-armory commented
@aleon1220, you haven't committed and pushed the requested changes, and the source repo has been deleted.

2020-04-29 19:45 UTC, aleon1220 commented
@brian-armory  So sorry the branch was removed. I had to create a new PR with the suggested changes: https://github.com/spinnaker/spinnaker.github.io/pull/1825

2020-04-29 22:32 UTC, closed without merging