Update slack-map.md
spinnaker/spinnaker.github.io pull request #1892
Opened 2020-06-25 17:15 UTC by ptr-dang

Removed all excessive activity channels to consolidate chatter onto #gardening-general, #gardening-ineedhelp, and #gardening-training

2020-06-25 17:18 UTC, dnilasor requested changes
Yay @ptr-dang first PR! Welcome to the Docs SIG. The pare-down is welcome, but I have a couple changes to request because I think we still need some additional channels : )

2020-06-25 17:40 UTC, ptr-dang reviewed
Looks good to me!

2020-07-22 20:42 UTC, dnilasor approved these changes

2020-07-22 20:42 UTC, dnilasor commented on community/gardening/slack-map.md
>  |#gardening-team-[projectString]|Team channels. projectString = repo name|
```suggestion
|#gardening-team-[projectString]|Team channels. projectString = repo name|
|[#spinnaker-tips](https://spinnakerteam.slack.com/archives/C011HAWD3M3)|Share Spinnaker tips for Spinnaker.io & Twitter mention and contribution points|
|[#spinnaker-news](https://spinnakerteam.slack.com/archives/C011W1CNW8Y)|Share Spinnaker news & content for upcoming Spinnaker.io mentions and contribution points|
|[#gardening-anonymous](https://spinnakerteam.slack.com/archives/C011BMZCS15)|Instead of a survey, we'll use Slack to transparently yet anonymously collect feedback|

```

2020-08-05 19:10 UTC, merged