docs(new spincli features): update spincli documentation
spinnaker/spinnaker.github.io pull request #1987
Opened 2020-07-24 14:46 UTC by Chinikins

This documents new features for the spin CLI.

For projects, these features reference:
https://github.com/spinnaker/spin/pull/261
https://github.com/spinnaker/spin/pull/260
https://github.com/spinnaker/spin/pull/258
https://github.com/spinnaker/spin/pull/270

For pipelines, these features reference:
https://github.com/spinnaker/spin/pull/280
https://github.com/spinnaker/spin/pull/278

While these features are in current master, I'm unsure of how coordination with spin cli releases and documentation get coordinated, but thought I'd open the PR since its in master for spin CLI.

2020-07-30 23:48 UTC, 317brian requested changes
Thanks for documenting the work you did! I have a few specific comments to address. Some general suggestions:
* Add comments in the CLI examples since this is brand new functionality. 
* The new page needs to be added to `_data/navigation.yml` so that it appears in the navigation. Currently the page is only accessible if I go to the page URL directly:
![image](https://user-images.githubusercontent.com/53799971/88985194-7f364300-d284-11ea-90e9-12684c7a9489.png)
There's already an existing section w/ the other `spin` pages, so you should be able to just copy those.

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/projects/index.md
> +managing your Spinnaker pipelines.
This should be `managing your Spinnaker projects` shouldn't it?

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/pipeline/index.md
> +Pipeline updated
`spin` returns `Pipeline updated` when the command is successful I'm assuming? Does it return an error if it fails?

Maybe add 
```
# Returns the following message if the pipeline gets updated successfully.

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/pipeline/index.md
> +Pipeline updated
Same as above

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/pipeline/index.md
> +### Enable/Disable a pipeline with `update`
```suggestion
### Enable/disable a pipeline with `update`
```

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/projects/index.md
> +listening on `http://localhost:8084`. If gate is running elsewhere,
Capital `G` on Gate.

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/projects/index.md
> +## Managing Your Pipeline's Lifecycle
```suggestion
## Managing your pipeline's lifecycle
```

2020-07-30 23:48 UTC, brian-armory commented on guides/spin/projects/index.md
> +Parsed submitted project: <...>
What gets returned in `<...>`?

2020-08-04 15:44 UTC, 317brian approved these changes
LGTM. I'm not sure when the spincli version with your changes will be released, so please coordinate with the release manager @kevinawoo on when to merge the docs. 

Thanks for working on this!

2020-08-04 15:44 UTC, 317brian approved these changes
LGTM. I'm not sure when the spincli version with your changes will be released, so please coordinate with the release manager @kevinawoo on when to merge the docs. 

Thanks for working on this!

2020-08-05 01:40 UTC, kevinawoo commented
Those new features are for 1.22, but they're on `master` right now. @brian-armory should we only merge it after 1.22 has been released?

[Here's the calendar](https://spinnaker.io/community/releases/release-cadence/#upcoming-releases). It looks like it's suppose to go out around 8/24.

2020-08-05 19:19 UTC, brian-armory commented
Cool, let's merge this when it's available in a release on Aug 24.

2020-08-25 18:18 UTC, Chinikins commented
@kevinawoo  @brian-armory  can this get merged now that @german-muzquiz has released spin 1.18.0? :tada:

2020-08-25 19:48 UTC, brian-armory commented
I'll merge it now. Thanks for following up @Chinikins!

2020-08-25 19:49 UTC, merged