Patching changelogs
spinnaker/spinnaker.github.io pull request #2031
Opened 2020-09-16 19:30 UTC by dbyron0

For background, see https://github.com/spinnaker/spinnaker.github.io/issues/2029

2020-09-16 20:23 UTC, dorbin commented on community/releases/index.md
> +* [Release Manager Runbook](/community/releases/manager-runbook/)
```suggestion
* [Release Manager Runbook](/community/releases/release-manager-runbook/)
```

2020-10-24 15:40 UTC, dnilasor requested changes
This looks fine to me. @brian-armory I'm not sure where exactly fits in the architecture of the new site (https://github.com/spinnaker/spinnaker.io - migration is in progress now and will be completed this year, for your reference @dbyron0), or if it makes more sense to add this as a section of a page rather than its own section of the nav. Regardless, seems like important information to share and I appreciate @dbryon0 for the PR! I made some minor suggestions for the language.

2020-10-24 15:40 UTC, dnilasor commented on community/releases/patching-changelogs/index.md
> +please contact the Release Manager via [slack](http://join.spinnaker.io), on
```suggestion
please contact the Release Manager via [slack](http://join.spinnaker.io), in
```

2020-10-24 15:40 UTC, dnilasor commented on community/releases/patching-changelogs/index.md
> +[#spinnaker-releases](https://spinnakerteam.slack.com/messages/spinnaker-releases/)
```suggestion
the [#spinnaker-releases](https://spinnakerteam.slack.com/messages/spinnaker-releases/) channel.
```

2020-10-24 15:40 UTC, dnilasor commented on community/releases/patching-changelogs/index.md
> +To change a [changelog](https://github.com/spinnaker/spinnaker.github.io/blob/master/_changelogs),
```suggestion
Release Managers are responsible for handling edits to existing changelogs. To request a change to a [changelog](https://github.com/spinnaker/spinnaker.github.io/blob/master/_changelogs),
```

2020-10-24 15:40 UTC, dnilasor commented on community/releases/patching-changelogs/index.md
> +please contact the Release Manager via [slack](http://join.spinnaker.io), on
```suggestion
please contact the Release Manager via [Spinnaker Slack](http://join.spinnaker.io), on
```

2020-10-24 15:40 UTC, dnilasor commented on community/releases/patching-changelogs/index.md
> +to handle edits to existing changelogs.
```suggestion
```

2020-10-26 17:30 UTC, dbyron0 commented on community/releases/patching-changelogs/index.md
> +please contact the Release Manager via [slack](http://join.spinnaker.io), on
https://github.com/spinnaker/spinnaker.github.io/pull/2031/commits/2796a64e735491e40469d993b26061b66fd0445b

2020-11-03 14:53 UTC, dogonthehorizon commented
@mergifyio refresh

2020-11-03 14:54 UTC, dogonthehorizon approved these changes

2020-11-03 14:55 UTC, dogonthehorizon commented
@mergifyio rebase

2020-11-03 15:05 UTC, dogonthehorizon commented
@mergifyio update

2020-11-03 15:31 UTC, dogonthehorizon commented
@dbyron0 would you mind rebasing off master? Should be good to merge when the build passes after that. Mergify doesn't seem to be playing nice this morning :(

2020-11-03 16:10 UTC, dbyron0 commented
@dogonthehorizon done

2020-11-03 17:23 UTC, merged

2020-12-17 18:48 UTC, dbyron0 commented
closes https://github.com/spinnaker/spinnaker.github.io/issues/2029