docs(aws): AWS Launch Template only applicable for 1.23 and above, upd…
spinnaker/spinnaker.github.io pull request #2098
Opened 2020-12-01 23:41 UTC by phebe-vickers

…ated instructions.

2020-12-01 23:59 UTC, brian-armory commented
Can you PTAL for the technical side @kevinawoo

2020-12-02 01:58 UTC, phebe-vickers commented
Forgot to note that this resolves Issue: https://github.com/spinnaker/spinnaker.github.io/issues/2091
Customer logged issue here and then reached out to Armory Support to find a solution.
This PR is the solution we tested and found.

2020-12-02 05:01 UTC, kevinawoo requested changes
Added some comments for the review.

@brian-armory do we have a process for 1.24 to remember to uncomment out these sections?

2020-12-02 05:01 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> -    aws.features.launch-templates.excluded-applications: "dangerousapp"
the flag `aws.features.launch-templates.excluded-application` was introduced in 1.23 by https://github.com/spinnaker/clouddriver/pull/4955, so we should still include it.

2020-12-02 05:01 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> -    aws.features.launch-templates.all-applicaitons.enabled: false
```suggestion
    aws.features.launch-templates.all-applications.enabled: false
```

the flag 
`aws.features.launch-templates.all-applicaitons.enabled` should be 
`aws.features.launch-templates.all-applications.enabled` (there's a typo in the docs)

and this was introduced in 1.24 by https://github.com/spinnaker/clouddriver/pull/5032, so removing it or commenting it out for 1.23 is fine.

2020-12-02 05:01 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> +  window.spinnakerSettings.providers.aws.serverGroups = {
We shouldn't override the whole `serverGroups` block, otherwise if https://github.com/spinnaker/deck/blob/master/settings.js#L152-L156 ever adds new keys, `settings-local.js` would override `settings.js` and confusion would be had.

Instead, it should be
```js
// enable launch templates for AWS
window.spinnakerSettings.providers.aws.serverGroups.enableLaunchTemplates = true;
window.spinnakerSettings.providers.aws.serverGroups.enableIPv6 = true;
window.spinnakerSettings.providers.aws.serverGroups.enableIMDSv2 = true;
```

2020-12-02 05:01 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> +<!-- The New to AWS section is valid in version 2.24 and later>
```suggestion
<!-- The New to AWS section is valid in version 2.24 and later
```

I think there's a syntax error if we're going to be commenting out this block

2020-12-02 05:01 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> +<!-- The New to AWS section is valid in version 2.24 and later>
```suggestion
<!-- The New to AWS section is valid in version 2.24 and later
```

I think there's a syntax error if we're going to be commenting out this block.

2020-12-02 17:38 UTC, phebe-vickers commented on setup/features/aws-launch-templates/index.md
> -    aws.features.launch-templates.excluded-applications: "dangerousapp"
Thanks Kevin, I thought that line did not exist until 1.24 - thanks for confirming it is part of 1.23, so it makes sense to add it.
As per a process for 1.24 we have PR: https://github.com/spinnaker/spinnaker.github.io/pull/2100

2020-12-02 18:13 UTC, phebe-vickers commented on setup/features/aws-launch-templates/index.md
> +  window.spinnakerSettings.providers.aws.serverGroups = {
Thanks for explaining this! That makes sense.

2020-12-02 21:48 UTC, kevinawoo commented on setup/features/aws-launch-templates/index.md
> +  window.spinnakerSettings.providers.aws.serverGroups = {
we should change this in the doc to the code block above

2020-12-03 01:05 UTC, phebe-vickers commented on setup/features/aws-launch-templates/index.md
> +  window.spinnakerSettings.providers.aws.serverGroups = {
Thanks Kevin, I have made the changes as suggested and  pushed it.

2020-12-03 05:42 UTC, kevinawoo approved these changes

2020-12-03 05:43 UTC, merged