docs(success-stories): Add Biden for President quote
spinnaker/spinnaker.github.io pull request #2152
Opened 2021-03-16 20:41 UTC by prophen

I added the quote from Matt Hodges, Engineering Director, Biden For President to the testimonials section in `/success-stories`

2021-03-16 20:42 UTC, prophen commented
@brian-armory please review, thank you

2021-03-17 17:29 UTC, aimeeu requested changes
@prophen Nikema - thanks for the update. Couple of concerns - since there's no logo, that space appears as a broken image.  Also, there's nothing in the "Click here to learn more" section.  It looks like these success stories involved interviewing the user? Not really sure how to proceed with this.

https://s.armory.io/WnuBoq05

2021-03-19 02:53 UTC, prophen commented
> @prophen Nikema - thanks for the update. Couple of concerns - since there's no logo, that space appears as a broken image. Also, there's nothing in the "Click here to learn more" section. It looks like these success stories involved interviewing the user? Not really sure how to proceed with this.
> 
> https://s.armory.io/WnuBoq05

Thanks, @aimeeu. I addressed your concerns with the latest commit. The quote is now in the case studies section along with an image so it doesn't break the design 
![image](https://user-images.githubusercontent.com/3941856/111725053-8b770c80-8823-11eb-8f14-8aba43b93514.png)

2021-03-19 14:42 UTC, aimeeu requested changes

2021-03-19 14:42 UTC, aimeeu commented on _data/success-stories.yml
> +    link: https://spinnaker.io/guides/
Wondering why this link is to the Spinnaker docs? In other Case Studies, the "Learn" link goes to a whitepaper or external site with an actual case study. Is it possible to link to wherever that quote appeared?  twitter, news site, ??

2021-03-22 21:58 UTC, prophen commented
![image](https://user-images.githubusercontent.com/3941856/112063517-c24c6b80-8b1e-11eb-9df5-9e8e40394b38.png) I created a new section for the quote so that it isn't out of place with the testimonials or case studies. What do you think, @aimeeu ?

2021-03-22 22:08 UTC, aimeeu approved these changes

2021-03-22 22:08 UTC, merged